Compute Good_turing estimate
dliyanage/AFLplusplus pull request #1
Opened 2023-09-01 08:37 UTC by dliyanage

2023-09-01 09:07 UTC, mboehme reviewed
As discussed.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-run.c
> +    if (unlikely(!diff_us)) { diff_us = 1; }
Revert.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-bitmap.c
>    }
Revert (Redundant).

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> -      afl->n_fuzz[cksum % N_FUZZ_SIZE]++;
Here we are tracking hit counts. We are only interested in the number of singletons, whether reset or not.
So, let's define a global variable called `singletons`, and 
* every time `afl->nfuzz[cksum % N_FUZZ_SIZE] == 0` before the hit count increment, we increment `singletons`.
* every time `afl->nfuzz[cksum % N_FUZZ_SIZE] == 1` before the hit count increment, we decrement `singletons`.

This optimizes the computation of singletons. You don't need to go through the entire array.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-stats.c
> +    }
Now redundant.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +    if (afl->queued_paths % 10 == 0) {
Make constant a "variable". For instance, see other constants in afl-fuzz.h.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +      memset(afl->n_fuzz_stats, 0, N_FUZZ_SIZE * sizeof(u32));
Now, you can set `singletons = 0`.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-stats.c
> +        u64 gt = (singletons /afl->fsrv.total_execs);
Here you redefine gt in a local scope. As soon as you leave the if statement, the value is forgotten.
Instead, remove the variable type (u64) to let this value be assigned to src/afl-fuzz-stats.c#L254.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-stats.c
> +      "good-turing       : %llu\n"
Also print it to plot_data.

2023-09-01 09:07 UTC, mboehme commented on src/afl-fuzz-stats.c
> +      "good-turing       : %llu\n"
Line 490.

2023-09-08 09:08 UTC, mboehme requested changes
Thanks! Several suggested changes below.

2023-09-08 09:08 UTC, mboehme commented on include/afl-fuzz.h
>  #define N_FUZZ_SIZE (1 << 21)
```C
#define RESET_PARAM  1 /* 10 */
```

2023-09-08 09:08 UTC, mboehme commented on include/afl-fuzz.h
> +      reset_param,                      /* The number of seeds to add before resetting the hit counts */
Substitute with constant (see below).

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +  afl->reset_param = 1;
Remove (once you have that as a constant)

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +      }
Comment this.

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +    }
Uncomment this, but set `afl->singletons = 0` whenever everything else is set up, too.

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +      afl->singletons_reset--;
```C
if (afl->n_fuzz[cksum % N_FUZZ_SIZE] == 0 ) afl->singletons++;
if (afl->n_fuzz_reset[cksum % N_FUZZ_SIZE] == 0 ) afl->singletons_reset++;
```

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +      afl->singletons_reset++;
```C
if (afl->n_fuzz[cksum % N_FUZZ_SIZE] == 1) afl->singletons--;
if (afl->n_fuzz_reset[cksum % N_FUZZ_SIZE] == 1) afl->singletons_reset--;
```

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-bitmap.c
> +    if (afl->queued_favored % afl->reset_param == 0) {
```C
if ((afl->queued_items % RESET_PARAM) == 0) {
  memset(afl->n_fuzz_reset, 0, N_FUZZ_SIZE * sizeof(u32));
  afl->singletons_reset = 0;
}
```

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz.c
> +    afl->n_fuzz_reset = ck_alloc(N_FUZZ_SIZE * sizeof(u32));
```C
afl->singletons = 0;
afl->singletons_reset = 0;
```

2023-09-08 09:08 UTC, mboehme commented on src/afl-fuzz-stats.c
> +        afl->gt_reset = (afl->singletons_reset / afl->fsrv.total_execs);
```C
afl->gt = ((double) afl->singletons) / afl->fsrv.total_execs;
afl->gt_reset = ((double) afl->singletons_reset) / afl->fsrv.total_execs;
```

2023-09-11 00:35 UTC, dliyanage commented
All changes implemented. Both general and 1-reset Good-Turing estimators now computed well. See the below outputs.
![Screenshot 2023-09-11 at 10 28 36 am](https://github.com/dliyanage/AFLplusplus/assets/57780422/8791df89-e5b4-4ab4-9e4c-37214a4d663f)
![Screenshot 2023-09-11 at 10 28 52 am](https://github.com/dliyanage/AFLplusplus/assets/57780422/860b328c-2caf-48fe-b052-de249d640f93)

2023-09-11 15:23 UTC, mboehme commented
Nice! 

Just wanted to check something. Instead of the floating point result, can you print the number of singletons (and reset singletons)? This way, we measure singletons, I suspect f1 to increase proportionally to the total number of generated inputs (i.e., almost everything is a singleton).

2023-09-15 10:51 UTC, mboehme approved these changes

2023-09-15 10:51 UTC, merged